<a href="https://colab.research.google.com/github/azyaf/RAG-Project/blob/main/Data_Retrieval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#from google.colab import userdata

#GITHUB_TOKEN    = userdata.get('GITHUB_TOKEN')
#GITHUB_USERNAME = "azyaf"
#REPO_NAME       = "RAG-Project"

#!git clone https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git
#%cd {REPO_NAME}

In [3]:
!git config --global user.email "andifayzamaharani@gmail.com"
!git config --global user.name "azyaf"

In [4]:
!pip install datasets faiss-cpu sentence-transformers -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 97.8 MB/s eta 0:00:00

In [5]:
import numpy as np
import pickle
import faiss
from datasets import load_dataset
from sentence_transformers import SentenceTransformer

In [6]:
dataset = load_dataset("rifkiaputri/idk-mrc")

print(dataset)
print("\nSample:")
print(dataset['train'][0])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/6.55k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

train.json:   0%|          | 0.00/3.90M [00:00<?, ?B/s]

valid.json:   0%|          | 0.00/350k [00:00<?, ?B/s]

test.json:   0%|          | 0.00/382k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3659 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/358 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/378 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['qas', 'context'],
        num_rows: 3659
    })
    validation: Dataset({
        features: ['qas', 'context'],
        num_rows: 358
    })
    test: Dataset({
        features: ['qas', 'context'],
        num_rows: 378
    })
})

Sample:
{'qas': [{'answers': [{'answer_start': 26, 'text': 'Pasuruan, Jawa Timur'}], 'id': 'indonesian-1653118927826418646-2', 'is_impossible': False, 'question': 'dimanakah  Dr. Ernest François Eugène Douwes Dekker dilahirkan?'}, {'answers': [], 'id': 'indonesian-2988585593205955820-unans-h-2', 'is_impossible': True, 'question': 'di manakah  Dr. Ernest François Eugène Douwes Dekker meninggal?'}], 'context': 'Douwes Dekker terlahir di Pasuruan, Jawa Timur, pada tanggal 8 Oktober 1879, sebagaimana yang dia tulis pada riwayat hidup singkat saat mendaftar di Universitas Zurich, September 1913. Ayahnya, Auguste Henri Edoeard Douwes Dekker, adalah seorang agen di bank kelas kakap Nederlandsch Indisch Escomptobank. Auguste ayahnya, memiliki darah Belanda dari ayahnya, Jan (adik Eduard Douwes Dekker) dan dari ibunya, Louise Bousquet. Sementara itu, ibu Douwes Dekker, Louisa Neumann, lahir di Pekalongan, Jawa Tengah, dari pasangan Jerman-Jawa.[1] Dia terlahir sebagai anak ke-3 dari 4 bersaudara, dan keluarganya pun sering berpindah-pindah. Saudaranya yang perempuan dan laki-laki, yakni Adeline (1876) dan Julius (1878) terlahir sewaktu keluarga Dekker berada di Surabaya, dan adik laki-lakinya lahir di Meester Cornelis, Batavia (sekarang Jatinegara, Jakarta Timur pada tahun 1883. Dari situ, keluarga Dekker berpindah lagi ke Pegangsaan, Jakarta Pusat.[1]'}

In [7]:
sample = dataset['train'][0]
print("Fields:", list(sample.keys()))

print("\nContext:", sample['context'][:200])

print("\nJumlah QA pairs:", len(sample['qas']))
print("\nSample:")
print("  Question  :", sample['qas'][0]['question'])
print("  Answers   :", sample['qas'][0]['answers'])
print("  Impossible:", sample['qas'][0]['is_impossible'])

Fields: ['qas', 'context']

Context: Douwes Dekker terlahir di Pasuruan, Jawa Timur, pada tanggal 8 Oktober 1879, sebagaimana yang dia tulis pada riwayat hidup singkat saat mendaftar di Universitas Zurich, September 1913. Ayahnya, August

Jumlah QA pairs: 2

Sample:
  Question  : dimanakah  Dr. Ernest François Eugène Douwes Dekker dilahirkan?
  Answers   : [{'answer_start': 26, 'text': 'Pasuruan, Jawa Timur'}]
  Impossible: False

In [8]:
raw_contexts = dataset['train']['context']

unique_contexts = list(set(raw_contexts))
print(f"Total raw context : {len(raw_contexts)}")
print(f"Total unique context  : {len(unique_contexts)}")

corpus = {i: text for i, text in enumerate(unique_contexts)}
doc_ids   = list(corpus.keys())
doc_texts = list(corpus.values())

print(f"\nSample corpus[0]: {corpus[0][:150]}...")

Total raw context : 3659
Total unique context  : 3659

Sample corpus[0]: São Paulo merupakan sebuah hub transportasi internasional di Amerika Selatan karena letaknya di berbagai rute perdagangan darat dan udara. Saat ini, a...

In [9]:
qa_pairs = []

for item in dataset['train']:
    context = item['context']
    for qa in item['qas']:
        if not qa['is_impossible'] and len(qa['answers']) > 0:
            qa_pairs.append({
                'question' : qa['question'],
                'answer'   : qa['answers'][0]['text'],
                'context'  : context,
            })

print(f"Total QA pairs yang bisa dijawab: {len(qa_pairs)}")
print(f"\nSample:")
print(f"  Q: {qa_pairs[0]['question']}")
print(f"  A: {qa_pairs[0]['answer']}")

Total QA pairs yang bisa dijawab: 5042

Sample:
  Q: dimanakah  Dr. Ernest François Eugène Douwes Dekker dilahirkan?
  A: Pasuruan, Jawa Timur

In [10]:
model_name = "paraphrase-multilingual-MiniLM-L12-v2"
embedding_model = SentenceTransformer(model_name)

print(f"Model loaded: {model_name}")

test_vec = embedding_model.encode("Apa ibu kota Indonesia?")
print(f"Shape vector: {test_vec.shape}")

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.89k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Model loaded: paraphrase-multilingual-MiniLM-L12-v2
Shape vector: (384,)

In [11]:
doc_embeddings = embedding_model.encode(
    doc_texts,
    batch_size=64,
    show_progress_bar=True
)

doc_embeddings = np.array(doc_embeddings).astype('float32')

print(f"\nShape embeddings: {doc_embeddings.shape}")

Batches:   0%|          | 0/58 [00:00<?, ?it/s]

Shape embeddings: (3659, 384)

In [12]:
dimension = doc_embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(doc_embeddings)

print(f"Total vektor dalam index: {index.ntotal}")

Total vektor dalam index: 3659

In [13]:
with open("corpus.pkl", "wb") as f:
    pickle.dump(corpus, f)

with open("qa_pairs.pkl", "wb") as f:
    pickle.dump(qa_pairs, f)

faiss.write_index(index, "faiss_index.bin")

In [14]:
def retrieve(query: str, k: int) -> list:
    query_vector = embedding_model.encode([query])
    query_vector = np.array(query_vector).astype('float32')

    distances, indices = index.search(query_vector, k)

    results = []
    for rank, (dist, idx) in enumerate(zip(distances[0], indices[0])):
        results.append({
            'doc_id' : doc_ids[idx],
            'text'   : corpus[doc_ids[idx]],
            'score'  : float(dist),
            'rank'   : rank + 1
        })

    return results

In [15]:
sample_question = qa_pairs[0]['question']
print(f"Query: {sample_question}\n")

for k in [1, 3, 5, 10]:
    results = retrieve(sample_question, k=k)
    print(f"--- K = {k} ---")
    for res in results:
        print(f"  Rank {res['rank']} | Doc ID: {res['doc_id']} | Score: {res['score']:.4f}")
        print(f"  Preview: {res['text'][:100]}...")
    print()

Query: dimanakah  Dr. Ernest François Eugène Douwes Dekker dilahirkan?

--- K = 1 ---
  Rank 1 | Doc ID: 907 | Score: 8.0431
  Preview: Douwes Dekker terlahir di Pasuruan, Jawa Timur, pada tanggal 8 Oktober 1879, sebagaimana yang dia tu...

--- K = 3 ---
  Rank 1 | Doc ID: 907 | Score: 8.0431
  Preview: Douwes Dekker terlahir di Pasuruan, Jawa Timur, pada tanggal 8 Oktober 1879, sebagaimana yang dia tu...
  Rank 2 | Doc ID: 3064 | Score: 12.9220
  Preview: Desiderius Erasmus dilaporkan lahir di Rotterdam pada tanggal 28 Oktober, di akhir tahun 1460-an.[1]...
  Rank 3 | Doc ID: 2352 | Score: 14.6997
  Preview: Émilie Du Châtelet lahir di Paris, Perancis, pada17 December 1706 dari pasangan Baron Louis Nicholas...

--- K = 5 ---
  Rank 1 | Doc ID: 907 | Score: 8.0431
  Preview: Douwes Dekker terlahir di Pasuruan, Jawa Timur, pada tanggal 8 Oktober 1879, sebagaimana yang dia tu...
  Rank 2 | Doc ID: 3064 | Score: 12.9220
  Preview: Desiderius Erasmus dilaporkan lahir di Rotterdam pada tanggal 28 Oktober, di akhir tahun 1460-an.[1]...
  Rank 3 | Doc ID: 2352 | Score: 14.6997
  Preview: Émilie Du Châtelet lahir di Paris, Perancis, pada17 December 1706 dari pasangan Baron Louis Nicholas...
  Rank 4 | Doc ID: 3189 | Score: 15.5120
  Preview: Anak Mojokerto, juga dikenal sebagai Mojokerto 1 dan Perning 1, adalah fosil bagian atas tengkorak d...
  Rank 5 | Doc ID: 3609 | Score: 15.7104
  Preview: Rene Descartes sering disebut sebagai bapak filsafat modern. Rene Descartes lahir di La Haye Tourain...

--- K = 10 ---
  Rank 1 | Doc ID: 907 | Score: 8.0431
  Preview: Douwes Dekker terlahir di Pasuruan, Jawa Timur, pada tanggal 8 Oktober 1879, sebagaimana yang dia tu...
  Rank 2 | Doc ID: 3064 | Score: 12.9220
  Preview: Desiderius Erasmus dilaporkan lahir di Rotterdam pada tanggal 28 Oktober, di akhir tahun 1460-an.[1]...
  Rank 3 | Doc ID: 2352 | Score: 14.6997
  Preview: Émilie Du Châtelet lahir di Paris, Perancis, pada17 December 1706 dari pasangan Baron Louis Nicholas...
  Rank 4 | Doc ID: 3189 | Score: 15.5120
  Preview: Anak Mojokerto, juga dikenal sebagai Mojokerto 1 dan Perning 1, adalah fosil bagian atas tengkorak d...
  Rank 5 | Doc ID: 3609 | Score: 15.7104
  Preview: Rene Descartes sering disebut sebagai bapak filsafat modern. Rene Descartes lahir di La Haye Tourain...
  Rank 6 | Doc ID: 3641 | Score: 15.7544
  Preview: Berawal pada akhir abad ke 17 seorang saudagar Belanda, eks VOC, bernama Cornelis Chastelein (1657–1...
  Rank 7 | Doc ID: 1454 | Score: 15.7571
  Preview: Gedung Sate yang pada masa Hindia Belanda itu disebut Gouvernements Bedrijven (GB), peletakan batu p...
  Rank 8 | Doc ID: 725 | Score: 15.9511
  Preview: dr. Tjipto Mangoenkoesoemo (EYD: Cipto Mangunkusumo) (Pecangaan, Jepara, Jawa Tengah, 1886 – Jakarta...
  Rank 9 | Doc ID: 3313 | Score: 15.9546
  Preview: Stephen dari Inggris atau Étienne (lahir sek. 1096 - wafat 25 Oktober 1154 pada usia 57 tahun), juga...
  Rank 10 | Doc ID: 2153 | Score: 15.9976
  Preview: Theodore Beza lahir di Vézelay, dalam wilayah Burgundy, Perancis. Ayahnya, Pierre de Beze, royal gov...

In [16]:
def get_context_for_generation(query: str, k: int) -> dict:
    retrieved_docs = retrieve(query, k=k)

    return {
        'query'    : query,
        'k'        : k,
        'documents': [
            {
                'doc_id' : doc['doc_id'],
                'text'   : doc['text'],
                'rank'   : doc['rank']
            }
            for doc in retrieved_docs
        ]
    }

# Test
output = get_context_for_generation(qa_pairs[0]['question'], k=3)

print(f"Query : {output['query']}")
print(f"K     : {output['k']}")
print(f"Jumlah dokumen retrieved: {len(output['documents'])}")
for doc in output['documents']:
    print(f"\n  [Doc {doc['rank']}] ID: {doc['doc_id']}")
    print(f"  Preview: {doc['text'][:150]}...")

Query : dimanakah  Dr. Ernest François Eugène Douwes Dekker dilahirkan?
K     : 3
Jumlah dokumen retrieved: 3

  [Doc 1] ID: 907
  Preview: Douwes Dekker terlahir di Pasuruan, Jawa Timur, pada tanggal 8 Oktober 1879, sebagaimana yang dia tulis pada riwayat hidup singkat saat mendaftar di U...

  [Doc 2] ID: 3064
  Preview: Desiderius Erasmus dilaporkan lahir di Rotterdam pada tanggal 28 Oktober, di akhir tahun 1460-an.[1][7] Ia dinamai seturut nama Santo Erasmus dari For...

  [Doc 3] ID: 2352
  Preview: Émilie Du Châtelet lahir di Paris, Perancis, pada17 December 1706 dari pasangan Baron Louis Nicholas le Tonnelier de Breteuil dan Gabrielle Anne de Fr...

In [17]:
!pip install -q transformers accelerate bitsandbytes sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 11.6 MB/s eta 0:00:00

In [18]:
import torch

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig
)

In [19]:
model_name = "Qwen/Qwen2.5-1.5B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True
)

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

print("Qwen loaded successfully!")

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Qwen loaded successfully!

In [20]:
def generate_answer(question, k):

    retrieved = get_context_for_generation(question, k)

    context = ""

    for doc in retrieved["documents"]:
        context += f"[Dokumen {doc['rank']}]\n{doc['text']}\n\n"

    messages = [
        {
            "role": "system",
            "content": "Anda adalah sistem Question Answering yang hanya boleh menjawab berdasarkan dokumen yang diberikan."
        },
        {
            "role": "user",
            "content": f"""
Dokumen:
{context}

Pertanyaan:
{question}

Jawab dengan format:

Jawaban: <jawaban singkat>

Sumber: Dokumen <nomor>

Jangan berikan penjelasan tambahan.
"""
        }
    ]

    # Buat chat template Qwen
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=2048
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=50,
        do_sample=False
    )

    # Ambil HANYA token hasil generate
    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    response = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    )

    return response.strip()

In [21]:
import re

def clean_prediction(text):

    if not isinstance(text, str):
        return ""

    # hapus Sumber: Dokumen 1
    # hapus Sumber: Dokumen [1]
    text = re.sub(
        r"Sumber\s*:\s*Dokumen\s*\[?\d+\]?",
        "",
        text,
        flags=re.IGNORECASE
    )

    # hapus Jawaban:
    text = re.sub(
        r"Jawaban\s*:\s*",
        "",
        text,
        flags=re.IGNORECASE
    )

    return text.strip()

In [22]:
import pandas as pd
import random

random.seed(42)

sample_size = 100

sampled_qa = random.sample(
    qa_pairs,
    sample_size
)

results = []

for k in [1, 3, 5, 10]:

    print(f"\n=== K = {k} ===")

    for item in sampled_qa:

        raw_prediction = generate_answer(
            item["question"],
            k=k
        )

        prediction = clean_prediction(
            raw_prediction
        )

        results.append({
            "k": k,
            "question": item["question"],
            "ground_truth": item["answer"],
            "prediction": prediction
        })

df_results = pd.DataFrame(results)

print(df_results.shape)

df_results.head()

=== K = 1 ===

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

=== K = 3 ===

=== K = 5 ===

=== K = 10 ===
(400, 4)

,k,question,ground_truth,prediction
0,1,berapakah jumlah sekuel Harry Potter?,tujuh,Jumlah sekuel Harry Potter adalah 8.
1,1,Kapan formula one pertama kali diselenggarakan ?,1950,Formula One pertama kali diselenggarakan pada ...
2,1,dari manakah Makhluk mitologis bernama genderu...,Pulau Jawa,dari mitologi Jawa
3,1,apakah arti kata Romusha?,buruh,Arti kata Romusha: Pekerja atau pekerjaan di I...
4,1,Kapan Aria Wiraraja lahir?,1232 Masehi,Aria Wiraraja lahir pada tahun 1257.

In [23]:
pd.set_option("display.max_colwidth", None)

df_results[
    ["question", "ground_truth", "prediction"]
].head(20)

,question,ground_truth,prediction
0,berapakah jumlah sekuel Harry Potter?,tujuh,Jumlah sekuel Harry Potter adalah 8.
1,Kapan formula one pertama kali diselenggarakan ?,1950,Formula One pertama kali diselenggarakan pada tahun 1950.
2,dari manakah Makhluk mitologis bernama genderuwo berasal?,Pulau Jawa,dari mitologi Jawa
3,apakah arti kata Romusha?,buruh,Arti kata Romusha: Pekerja atau pekerjaan di Indonesia yang dipekerjakan secara paksa oleh Jepang selama penjajahan mereka di Indonesia.
4,Kapan Aria Wiraraja lahir?,1232 Masehi,Aria Wiraraja lahir pada tahun 1257.
5,Siapakah nama pemimpin dalam gereja ?,Paus,Nama pemimpin dalam gereja adalah Yang Mulia Bapa Adolfo Nicolás.
6,Berapakah jarak Neptunus dengan Matahari?,101jutakm,Jarak antara Neptunus dan Matahari mencapai 101juta km.
7,umur berapakah Albert einstein meninggal?,76,Umur Einstein saat meninggal: 76 tahun.
8,Siapakah penegak hukum di Indonesia?,Kepolisian Negara Republik Indonesia,Letkol. Ventje Sumual
9,Apakah tujuan utama dibentuknya Mujahidin KOMPAK?,"membantu korban konflik dan bencana, kelompok ini telah dikaitkan dengan penyediaan dana untuk organisasi teroris seperti Jemaah Islamiyah serta melakukan serangan terhadap kelompok Kristen setempat",Tidak ada jawaban yang sesuai untuk pertanyaan tersebut karena informasi tentang tujuan pembentukan Mujahidin KOMPAK tidak ditemukan dalam dokumen yang diberikan.
10,Berapa luas wilayah Bayern?,70.553km²,Luas wilayah Bayern: 70.553 km²
11,Berapa lama Belanda menjajah Indonesia?,"3,5 abad","Sekitar 3,5 abad antara awal abad ke-17 hingga pertengahan abad ke-20."
12,Dimana Muhammad bin ʿAbd al-Wahhāb dilahirkan?,1115 H,"Syeikh Muhammad bin ʿAbd al-Wahhāb dilahirkan di kampung Uyainah (Najd), lebih kurang 70 km arah barat laut kota Riyadh"
13,Kapan Purnawarman lahir?,16 Maret 372 Masehi,30 Juni 1892
14,Dimana kantor pusat Google Inc?,"Mountain View, California","Mountain View, California."
15,Sungai apa yang terpanjang di Africa?,Nil,Sungai Nil.
16,Dimana Pertempuran Manzikert terjadi?,"dekat Manzikert, Kerajaan Armenia","Pertempuran Manzikert terjadi di dekat Manzikert, Kerajaan Armenia (saat ini Malazgirt, Turki)."
17,Siapa nama istri Bindusara ?,Subhadrangi,Subhadrangi
18,Siapa walikota Semarang tahun 2017?,Hendrar Prihadi,Hendra Prihadi
19,Dimana Ban Ki-moon lahir ?,Chungcheong Utara,"Ban Ki-moon lahir di Eumseong, Korea Selatan."